name: mattermost-build
on:
  pull_request:
  push:
    branches:
      - master
      - cloud
      - release-*
      - mono-repo*
env:
  go-version: "1.19.5"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains( github.ref , 'heads/ref/master') }}
jobs:
  test-postgres-normal:
    name: Run tests on postgres
    uses: ./.github/workflows/test.yml
    with:
      datasource: postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10
      drivername: postgres
